### PR TITLE
Created pf2.json

### PR DESCRIPTION
**Pull request by zarmstrong**
pf2.json file for pf2 conditions

### CODE REVIEW

**Comment by eclarke12** [comment]
@zarmstrong thanks for this! I specifically removed the PF2e condition mapping when the game system built their own condition management system. I'm concerned adding this back will cause some conflicts.

**Comment by zarmstrong** [comment]
Ah gotcha. I'm not sure of how to test that, but happy to if you could give some guidance.

**Comment by zarmstrong** [comment]
Ah that makes sense. No harm either way! :)

**Comment by eclarke12** [comment]
Hey @zarmstrong did you test this in a world? I don't use PF2e, but when I try adding a condition from the mapping you've provided, it fails to add it due to code in the PF2e system.

**Comment by zarmstrong** [comment]
Unfortunately I don't recall, it was a while ago.  I'll take a look and see if I can get it to work in one sometime this week and get back to ya.

**Pull request merged**
