### PR TITLE
Award XP dialog

### PR DESCRIPTION
**Pull request by Wibble199**
Adds an additional dialog that appears after the end combat confirmation that allows for configuration of how XP is given out.

Award XP dialog

- Can select which friendlies receive and which hostiles give XP.
- Dialog gives a breakdown of how much XP the party will receive and how much each player receives.
- Deselecting a friendly will flag it so it will be deselected by default next time XP is awarded (useful for recurring creatures that should not be awarded XP, such as companions).
- Can specify a multiplier that will be applied to all creature's XPs (default value is set in CUBPuter options).
- Chat message sent when characters get XP, and another when characters have enough to level up.
- Encounter deletion is deferred until after this dialog is "OK"ed.

Not sure if this is the best way to go about adding a dialog like this - this is my first proper dive into Foundry module dev. Would appreciate some feedback :)

### CODE REVIEW

**Comment by geoidesic** [comment]
I tried installing this but the extra dialog didn't appear.

**Comment by geoidesic** [comment]
It would be great to get this merged in guys. I've created my own fork so that I can begin using this in game already.

**Comment by geoidesic** [comment]
Just a note – this doesn't handle fractions well. It should round off to two decimal places.

**Comment by eclarke12** [comment]
Hi @Wibble199 I'm really sorry it's taken so long to get back to you on this--it looks amazing!

I'm pulling into the 08x working branch and I will patch the PR as necessary to provide compatibility with 08x as well as addressing any stylistic changes I need to make.

Thanks again!

**Comment by eclarke12** [comment]
@allcontributors please add @Wibble199 for code

**Pull request merged**
